apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: prometheus
  labels:
    helm.sh/chart: grafana-5.8.12
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "7.2.1"
data:
  grafana.ini: |
    [analytics]
    check_for_updates = false
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    root_url = http://localhost:3000/grafana
    serve_from_sub_path = true
    [security]
    admin_user = admin
    admin_password = admin
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local/prometheus
